- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
    - apache2
    - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for CentOS servers
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd service on CentOS
  tags: apache httpd, CentOS
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: change email address for admin
  tags: apache,ubuntu
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^ServerAdmin webmaster@localhost'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Ubuntu"
  register: apache2

- name: restart apache2 service(Ubuntu)
  tags: apache,ubuntu
  service:
    name: apache2
    state: restarted
  when: apache2.changed


- name: copy default html for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
